### ISSUE TITLE
Add support for sqlite

### ISSUE THREAD

**Issue by alimeerutech** [simplesurance/baur#150]
with sqlite supported you would not need to have a postgres instance hosted somewhere 24x7 would just keep the db with the code, makes life easier.

**Comment by fho** [comment]
How would you keep the db with the code?

**Comment by alimeerutech** [comment]
my suggestion would be to initialize the sqllite db with something like a

baur init

and save it as .baur.sqlite in the root of the same repo you want to use
the baur tool with.

**Comment by fho** [comment]
I assume you mean a Git repository and a workflow like:
- create branch from the mainline branch,
- build apps in CI,
- write build result to sqlite file,
- commit changed sqlite file to git repository

Some issues that come to my mind with this approach:

- the build results are only available in the same branch, other branch would not use the data version from when the branch was created, this would cause unnecessary rebuilds,
- when merging branches you will have merge conflicts in the sqlite database files. These will be impossible to resolve because it's a binary format.
- building apps from the same branch in parallel on multiple CI machines would not be possible

**Comment by alimeerutech** [comment]
makes sense, to overcome those issues I guess we would need a directory structure and one baur separate sqllite per branch but i guess that makes things more complicated, my thought is to *somehow* remove that dependency on an external db so the tool would be self sufficient

**Comment by fho** [comment]
Making the tool self sufficient would be great.
I currently don't know how this could be achieved without loosing major features though.
