### ISSUE TITLE
It's not possible to install baur using`go install` because of incorrect go.mod

### ISSUE THREAD

**Issue by kostyay** [simplesurance/baur#295]
Currently trying to install baur using
`go install github.com/simplesurance/baur@master` 
Will fail  with the following error due to incorrect package name defined in go.mod
`go install github.com/simplesurance/baur@master: github.com/simplesurance/baur@v0.16.1-0.20210316110754-e5ba6940fa93: invalid version: go.mod has malformed module path "github.com/simplesurance/baur/v1" at revision e5ba694`

It seems that there is some magic to support old config migration which is why the v1 was introduced.

**Comment by fho** [comment]
I added the `/v1` suffix because I though that is the correct standardized way to release a new major version with go-modules.
It turns out that go modules treat `/v1` suffix special.
v0 and v1 seem to have to use the same go module import path, without a version prefix, only from version 2 on a suffix for the major version like `/v2` is appended

The options to fix it that I see are:
- rename the module `github.com/simplesurance/baur/v1`  to `github.com/simplesurance/baur`, then I can not vendor via go-modules github.com/simplesurance/baur/cfg@v0.20.0 anymore. I will have to copy the cfg package from that version.
- skip version 1 entirely, change the module name from `github.com/simplesurance/baur/v1` to github.com/simplesurance/baur/v2`, create a 2.0.0-rc release

**Comment by kostyay** [comment]
In another issue you commented that the new version shouldnt be backward compatible, why do you need the config upgrade tool then?
How about implementing the config update tool in a separate repository?

**Comment by fho** [comment]
To make it easier to migrate to version 1 :-)

>  How about implementing the config update tool in a separate repository? 

I think I would have the same issue then only in another repository.
I would want to import the cfg package from v0 and from v1 to do the upgrade.
Importing the packages from v0 and v1 would only work if they have different module names.

**Comment by kostyay** [comment]
Perhaps copying the old config module would be the easiest solution then. Why not? Are you planning to release new updates for the old version that change the config structure?

**Comment by fho** [comment]
:+1: I also think that is the best solution.

**Comment by fho** [comment]
That solution did not work out, much more packages then the cfg packages would have been needed to be copied.
I'm also using the functions from v0 to discover the application configs which in turn import other packages. 
I'm jumping to version 2 instead (https://github.com/simplesurance/baur/pull/296).
