### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by maktouch** [simplesurance/baur#94]
Is Windows support something planned? There's no windows builds in the release. It's for building c++ and .net projects.

**Comment by maktouch** [comment]
Thinking about this - it would probably break some stuff like `baur build`. 

We have a monorepo with projects in c++ for windows, objective-c in osx, and the server components in node. 

For this to work, we'd need some kind of tagging system, similar to what the CI system have. 

Something like, 

On the UNIX CI machine, `BAUR_TAGS=linux,docker`
On the OSX CI machine `BAUR_TAGS=osx,xcode,docker`
On the Windows CI machine `BAUR_TAGS=windows,visual-studio`

Then 
- on the `.app.toml` of the OSX project, you'd have `tags = ["osx", "xcode"]`,
- on the windows project, you'd have `tags = ["windows", "visual-studio"]`,
- on the node projects, you'd have `tags = ["docker"]`

So that when you trigger `baur build`, only the corresponding tags gets built. For the node project, it would be able to run on either the OSX or the Unix machine since all it requires is docker.

**Comment by fho** [comment]
@maktouch Sorry, providing windows binaries is not planned.
You can compile baur on your own for Windows and try to run it.
baur was never tested on Windows though, you will probably run into some issues.
I would be happy to accept PRs to fix those and help with fixing smaller issues.

The idea to support app tags is great.
If it turns out baur would work for you on windows please create a separate Issue about adding support for tags.
